import {
  AlarmClock,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  Bell,
  BellOff,
  BookOpen,
  Bookmark,
  Briefcase,
  CalendarDays,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileImage,
  FileText,
  Gavel,
  GraduationCap,
  Home,
  Image,
  ImagePlus,
  Inbox,
  Info,
  KeyRound,
  ListChecks,
  LayoutDashboard,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  MessageSquare,
  MousePointerClick,
  PackageCheck,
  Palette,
  Paperclip,
  PartyPopper,
  PenLine,
  Plus,
  QrCode,
  Receipt,
  RotateCw,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  ShieldCheck,
  Star,
  Store,
  Tag,
  Trash2,
  Unlock,
  Upload,
  UserCheck,
  UserPlus,
  UserSearch,
  Users,
  Wallet,
  XCircle,
  ZoomIn,
} from "lucide-react";

/* Instagram dibuang: Lucide 1.x tidak lagi memuat ikon brand, dan tautan
   sosial lebih jelas ditulis sebagai teks bernama daripada glyph.

   Registri ikon tertutup, bukan impor dinamis dari seluruh Lucide.
   Dua alasan: hanya ikon yang benar-benar dipakai yang ikut ke bundel, dan
   menambah ikon jadi keputusan sadar, bukan refleks (antislop R-04). */
export const ICONS = {
  AlarmClock,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  Bell,
  BellOff,
  BookOpen,
  Bookmark,
  Briefcase,
  CalendarDays,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileImage,
  FileText,
  Gavel,
  GraduationCap,
  Home,
  Image,
  ImagePlus,
  Inbox,
  Info,
  KeyRound,
  ListChecks,
  LayoutDashboard,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  MessageSquare,
  MousePointerClick,
  PackageCheck,
  Palette,
  Paperclip,
  PartyPopper,
  PenLine,
  Plus,
  QrCode,
  Receipt,
  RotateCw,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  ShieldCheck,
  Star,
  Store,
  Tag,
  Trash2,
  Unlock,
  Upload,
  UserCheck,
  UserPlus,
  UserSearch,
  Users,
  Wallet,
  XCircle,
  ZoomIn,
} as const;

export type LucideName = keyof typeof ICONS;

/** Nama Lucide ditambah ikon PNG pilihan pemilik produk (lihat icon-gambar.ts). */
export type IconName = LucideName | import("./icon-gambar").NamaIkonGambar;
